### ISSUE TITLE
Support for Vulnerability Curves [VA API]

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#13]
Eventually we would need an API to access and modify the vulnerability curves stored in EMIKAT. ATM we just need some information we can put into the related [Data Package Resource for VA](https://github.com/clarity-h2020/data-package/issues/15). 

See also [this question](https://github.com/clarity-h2020/csis/issues/16#issuecomment-473814930): What can we *currently* put into he Data Package Description? Some static images + a description of the currently available vulnerability curves would be just enough!

**Comment by humerh** [comment]
As defined by PLINIVS in the Meeting in July in Vienna we dont have vulnerability curces any more.
The model of calculation has completly to be changed.

**Comment by humerh** [comment]
See also: https://newrepository.atosresearch.eu/remote.php/webdav/CLARITY/Events/Project%20Events/Plenary%20Meetings/2019-07-03_05%20Project%20Meeting%20(Vienna)/Presentations/Impact%20modelling%20HW_PLINIVS.pptx

**Comment by p-a-s-c-a-l** [comment]
So and what do we show on the VA Tab in CSIS? VA is part of the methodology!

Any ideas @bernhardsk @DenoBeno ?

**Comment by humerh** [comment]
Maybe you can show one (or more) of the diagrams on page  9-11

**Comment by p-a-s-c-a-l** [comment]
Yes that's what I've asked for [here](https://github.com/clarity-h2020/data-package/issues/15)! Maybe @bernhardsk is able to create the respective VA Resource in CSIS?

**Comment by humerh** [comment]
I cannot help to resolve this issue. Please @DenoBeno OR @patrickkaleta fix this.

**Comment by DenoBeno** [comment]
I need some time until I can do anything about this. If someone else can work on it, please do.

**Comment by DenoBeno** [comment]
https://newrepository.atosresearch.eu/remote.php/webdav/CLARITY/Events/Project%20Events/Plenary%20Meetings/2019-07-03_05%20Project%20Meeting%20(Vienna)/Presentations/Impact%20modelling%20HW_PLINIVS.pptx

**Comment by DenoBeno** [comment]
I have started working on this. There are basically two ways of implementing something "nice" for the vulnerability curves in Drupal:

1. By extending the dp_resource.
2. By adding a new content type.

At least for initial testing, I prefer the second approach. Thus, I have added a dp_vulnerability node type https://csis.myclimateservice.eu/admin/structure/types/manage/dp_vulnerability/fields

The next question is "what should be the data model"? Since the vulnerability links a hazard and element at risk (exposure) with risks and/or impacts, this is how the data model of dp_vulnerability must look like:

**1. Title
2. Some content to visualize** (TBD)
**3. link to a relevant hazard** (or hazards?)
**4. link to a relevant element at risk** (or elements at risk?)
5. some indication of a risk/impact this vulnerability curve will result in? (TBD)
6. Configuration file to be used by e.g. EMIKAT? (TBD)

For a start, I decided to implement the following data model, covering just the points 1-4

![image](https://user-images.githubusercontent.com/2961790/64533761-7529ef80-d314-11e9-9913-6376c8bf0a0f.png)

_For a start, simply visualizing some text and an illustration or two should do. We can discuss more complex approaches later._

The next step would be to embed this in the data package. In theory, this could be done by referencing the URI of the relevant dp_vulnerability from the dp_resource, but then we would have to write some javascript applications to present the data.

Alternatively, I could also add the necessary fields directly to dp_resource.

Less drastic approach would be to embed dp_vulnerability in the dp_datapackage in the same way as the Adaptation options:

![image](https://user-images.githubusercontent.com/2961790/64534281-790a4180-d315-11e9-8add-dc4e13e1018d.png)

That is, we could logically treat dp_vulnerability as a "type of" dp_resource
If done in this way, it would be easy to add drupal views  that visualize the vulnerability curves. 

**WDYT?**

**Comment by DenoBeno** [comment]
**FYI:** What I have in mind for the short-term is just to show the vulnerability curves. 

In the mid-term, I could follow the same  approach as for the adaptation options and add some data to these nodes that can be used by EMIKAT. This would allow us to eventually assure that adding new dp_vulnerability node to a data package (with correct data)  is all we need for EMIKAT to calculate the risk/impact. 

This is the "ideal" solutions that I have in my mind as a long-term vision for the dp_vulnerability node types.

**Comment by patrickkaleta** [comment]
> ...
> WDYT?

@DenoBeno 
Short answer: Looks good enough for me!

**Couple of notes:**
- I would probably prefer the second approach (model vulnerability as own content type) even for a long-term solution 
  - **1. reason:** would allow us to, at least partially, show vunerabilities without needing a datapackage or resource as context (just like adaptation options)
  - **2. reason:** the data model for resources is already pretty big, I wouldn't add anything else to it unless it's absolutely necessary
- in favor of embedding them in the datapackage as entity references and therefore treating them like adaptation options
- regarding the data model structure (and your points 2, 5 and 6), I think we could include @humerh in this discussion
- regarding the data model structure and the cardinality of hazards and el@risk, I think that we should:
  - **start of with a 1:1 relation** (since it's the easiest and it's not a problem in Drupal to switch a field from a single element to multiple elements) and then later maybe
  - have **1 hazard** with (potentially) **multiple elements at risk**
  - or (potentially) **multiple hazards** for just **1 element at risk**
  - but not mix **m** hazards with **n** elements at risk (would probably make it harder for us and just confuse end-users)

**Comment by DenoBeno** [comment]
First dp_vulnerability defined https://csis.myclimateservice.eu/node/1350
Looks nice IMO
![image](https://user-images.githubusercontent.com/2961790/64714792-86632f80-d4bf-11e9-8bf6-32b019fe4dc4.png)

Not sure which hazard this really relates to

**Comment by DenoBeno** [comment]
I have started looking at the "Impact modelling flooding" description and the first thing that strikes the eye is that this one is talking about:
- one hazard (flood), but which hazard indices? 
- FOUR elements at risk (buildings, industrial, roads, agricultural)
- (at least) two risk/impact indices for each combination of hazard & element at risk: direct and indirect damage; each in € and in % of the value 

I reckon that we should have just one hazard/element at risk per vulnerability curve, but we could pack several output indices in one dp_vulnerability?

WDYT? What would be the disadvantage if more than one output indicator is packed in?

--------------------
**Beyond showing nice pictures to visitors**
This is already interesting enough, but now comes the next question: if we want to make the vulnerability curves usable for the backend processing, we (EMIKAT) would need to know which resources/which references can be used as input for the calculation. this is complex, so I'll open a separate issue for it.

**Comment by DenoBeno** [comment]
I have implemented a way to associate the vulnerability curves with the data package and also to indicate which resources are used as input and where to look for the output of the risk/impact calculation. This is how it works:

1. I have added several edit forms for the data package. These are called step 1, step 2, ... in anticipation of the workflow module. They can already be used today, just without explicit workflow.
Step 1
![image](https://user-images.githubusercontent.com/2961790/64871321-4b8b0400-d645-11e9-92db-a328b9dde2cd.png)
Step 2
![image](https://user-images.githubusercontent.com/2961790/64871348-5a71b680-d645-11e9-80f3-a9aef449f974.png)
Step 3
![image](https://user-images.githubusercontent.com/2961790/64871369-678ea580-d645-11e9-9235-6ed4b3145a8c.png)
Step 4
![image](https://user-images.githubusercontent.com/2961790/64871397-77a68500-d645-11e9-9755-2c9ffc97f5e0.png)

The "VA relations" is a paragraph consisting of three fields that are filled in using a bit of a views magic.

![image](https://user-images.githubusercontent.com/2961790/64871551-bdfbe400-d645-11e9-9b3f-1e49f2f2ce39.png)
![image](https://user-images.githubusercontent.com/2961790/64871511-ac1a4100-d645-11e9-9502-6395c80edb0e.png)

end result:

the user can indicate what are the inputs (hazard, elements at risk, other) and outputs (risk/impact indicators) related to each of the vulnerability curves they added to the data package.

![image](https://user-images.githubusercontent.com/2961790/64871735-29de4c80-d646-11e9-9fb0-3cf82112b442.png)

**Comment by DenoBeno** [comment]
OK, so we have a possibility to define some vulnerability resources, add them to the DP, and see what has been added on the data package overview page:

https://csis.myclimateservice.eu/node/50
![image](https://user-images.githubusercontent.com/2961790/64872263-2d260800-d647-11e9-9c1a-bed101f74196.png)

OK, it's rudimentary but it's informative. Unfortunately, none of this is shown in the "vulnerability" step in the study.

**Comment by DenoBeno** [comment]
I have implemented a "quick and dirty" possibility to show vulnerability functions in the VA step. It's analogous to the way adaptation options table works.

![image](https://user-images.githubusercontent.com/2961790/64876576-ad506b80-d64f-11e9-9216-b570cd5e16ba.png)

This means that now the user has a possibility to easily decide which VFs to include in the report, the same as for the adaptation options. Only the buttons don't work yet (@patrickkaleta , pls fix.)

**Comment by DenoBeno** [comment]
Status update Friday, 13/09/2019
Technically, we are "almost there" to provide all the support EMIKAT could ever dream of. 
**IMPLEMENTED**
1. It's possible to define Vulnerability function nodes (dp_vulnerability). 
__Attaching the vulnerability function (table) data to this node would be trivial and will be done as soon as it's possible to visualise this data in Drupal (waiting for https://github.com/clarity-h2020/csis/issues/98)__
2. It's possible to indicate which vulnerability functions are relevant for the data package.
3. It's possible to indicate which resources are related to these vulnerability function as input and output in the data package. 
__once the https://github.com/clarity-h2020/docker-drupal/issues/114 is resolved, this will work even better__
4. It's possible to visualise the vulnerability functions and decide which ones to include in the report.
__This will work even better once the https://github.com/clarity-h2020/csis/issues/98) is resolved__

TODO:
1. Assure that EMIKAT can make use of this information
__providing this data to EMIKAT is a question of JSON:API, extending the "helpers module" or adding a special view to generate what EMIKAT needs. Not sure how urgent, but it should be done eventually__
2. Provide more/better vulnerability functions, including the actual data that's needed for calculations
3. Include this to data package/data packages
__ it's easy to do this for the "expert" data packages, more work for the "screening"__
4. various improvements, tbd.
5. other?

**Comment by patrickkaleta** [comment]
> This means that now the user has a possibility to easily decide which VFs to include in the report, the same as for the adaptation options. Only the buttons don't work yet (@patrickkaleta , pls fix.)

Done! Adding Vulnerability functions to a GL-step is now supported by the CSIS helpers module.

**Comment by DenoBeno** [comment]
@patrickkaleta : indeed add/remove works now.

**Comment by DenoBeno** [comment]
Now we can very easily implement a simple but functional API for accessing and updating the machine-readable vulnerability curves:

1. Allow the users to attach a csv or json file to the dp_vulnerability
2. This file can be accessed and replaced over JSON:API

Optional but nice and "cheap": 
3. Install the the chart suite (https://github.com/clarity-h2020/csis/issues/98) and we can visualise the curves on drupal too.

**Comment by DenoBeno** [comment]
This is labeled as "in progress" in T1.3. In reality, I have no idea what to do with it now and nobody else is working on it.

**Comment by humerh** [comment]
After the changes in the calculation of Impact we have no vulnerability curves any more.
The new Mortality function was implement already months ago.
Someone should close this issue.

**Comment by p-a-s-c-a-l** [comment]
> we have no vulnerability curves any more

OK, closing. But then I don't understand why [this](https://github.com/clarity-h2020/emikat/issues/13#issuecomment-531298983) has been implemented.

**Comment by DenoBeno** [comment]
Because we still have something playing the role of the va curve. And I
wasn't aware of this change.
