### ISSUE TITLE
New application proposal: x-t graphs

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/emikat#27]
Related to https://github.com/clarity-h2020/emikat/issues/23

For our last demo, Rose has prepared a fake report for the screening study of Alba Iulia. 

[CLARITY-CSIS_report_AlbaIulia.docx](https://github.com/clarity-h2020/emikat/files/3717449/CLARITY-CSIS_report_AlbaIulia.docx)

In this report, she has included several very simple but useful x-t graphs. Here is how they look like:

![grafik](https://user-images.githubusercontent.com/2961790/66650384-c2a9bd00-ec30-11e9-8457-5a1c40bd8dcc.png)

![grafik](https://user-images.githubusercontent.com/2961790/66650397-cfc6ac00-ec30-11e9-97b7-5692b8c50e24.png)

This has been varmly welcomed by the users. In my opinion, we should produce something similar on the fly. WDYT?

**Comment by DenoBeno** [comment]
I say "similar" because I am not sure if we have the data necessary to do exactly the same. 

For the **hazard indices produced by ZAMG**, we do have the uncertainty - just not in the same resource. We *could* merge the value + deviation resources (ensmean and ensstd) in one resource and then produce this type of graphs...

For this, we would have to:
1. define new reference types or qualifiers that differenciate between value and standard deviation of this value
2. change resource definitions (would be far less work if we first implement https://github.com/clarity-h2020/data-package/issues/47 first)
3. assure that this x-t graph applications takes the correct data and shows it.
4. (somewhat optional) also update the table and map applications to do somethign useful with this data.

For other resources, I am not sure if we have uncertainty. 
@humerh : do we have it for EMIKAT results?
@RobAndGo : do we have it for any other resources?

An alternative to showing uncertainties woudl be to show the results for all three climate scenarios. This can also be understood as a form of uncertainity, but I would rather see this as a different type of information that could also be of interest to the user.

**Comment by DenoBeno** [comment]
When I think of it... If we implement https://github.com/clarity-h2020/data-package/issues/47, then this type of graphs could (should?) be used to represent the resource on the data tab and possibly also on the resource page. (Since it combines different climate scenarios & times in one illustration, it )

**Comment by RobAndGo** [comment]
Hi @DenoBeno 
All the indices that we generate based on the EURO-CORDEX data consist of a mean (suffix _ensmean) and a standard deviation (suffix _ensstd) of all models considered in the ensemble. For the indices that I have uploaded, these have been done as separate resources because I wasn't sure if supplying the data together in one file was a valid option
1. for METEOGRID to do the conversion from netcdf to geotiff, and
2. for CSIS (I thought each resource had to consist of an individual layer).

**Comment by DenoBeno** [comment]
@RobAndGo : indeed, at the moment each ressource must consist of exactly one layer. However, the data+stdev is *logically* seen one piece of data and maybe we can change the way how we handle the data so that this logic is directly visible within the resource. 

This is all for discussion atm., because we have plenty of work to do and need to prioritise. Still, it's good to put things on the table while we still remember them.

**Comment by claudiahahn** [comment]
> I say "similar" because I am not sure if we have the data necessary to do exactly the same.

Just that you know what is displayed in the figures above: I used the min and max values from the ensemble to plot the range.

**Comment by humerh** [comment]
Isn't it possible to make such diagrams by the variables TIME_PERIOD and EMISSIONS_SCENARIO?
EMISSIONS_SCENARIOS span in my eyes also the probability space of future situation.
If we use these parameters then we have all information.

**Comment by RobAndGo** [comment]
@claudiahahn is currently too busy at the moment to answer, but when she made the plots, she thought of showing all 3 curves for the different RCPs in one by representing each in a different colour or shading, e.g.

RCP26 - blue (`#0000FF`) with light blue (`#A9A9F5`) error range.
RCP45 - cyan (`#00FFFF`) point with light cyan (`#A9F5F2`) error range.
RCP85 - magenta (`#FF00FF`) point with light magenta (`#F5A9F2`) error range

As there would be some overlap, one would need to adjust the transparency accordingly.
Colours green/yellow/red were avoided in order to prevent potential clashes with the colour scale used to classify the hazard intensity used in other parts of CSIS.

**Comment by p-a-s-c-a-l** [comment]
Doesn't seem that anybody is going to work on this. If this is true, we should close the issue and focus more on our core tasks.

**Comment by p-a-s-c-a-l** [comment]
Answer from Robert / Claudia:
> “If there are no resources available to implement this graph visualisation, then we have to let it be. Perhaps it may be useful to include a note somewhere (in a deliverable?) saying that such a data presentation would be good to have, but owing to the current constraints, it is not feasible to implement it”.
