### ISSUE TITLE
Damage level estimates table showing wrong calculations

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/emikat#3]
CLARITY impact table at https://csis.myclimateservice.eu/study/1/step/22/view/table shows unplausible results

E.g., the sum of all “old” people (D1++  D5)  is ca. 100k for 28° and ca. 20k for 34°. The rest moved out? :-D

Haet wave 34°, 6 days
people
Age>65
number of people
19,389
18,550
7,099
1,358
135

Heat wave 28°, 6 days
people
Age>65
number of people
43,278
41,406
15,846
3,032
301

**Comment by stefanon** [comment]
@bernhardsk Hi Bernard, I'm not really sure that the problem reported is due to missing set of data for different temperatures, or at least I don't understand well how it was done. I was ill last days, sorry to hear you wasn't able to contact anyone from PLINIVS, not even by email. 
By the way as I'm not able to login to CLARITY CSIS (never received the activation email) I can't check directly the problem, but for what I've seen in other discussions also the indicators for HW damage results have problems, as they show level of damage decreasing with increase of the temperature. Let me know if we can check and help in somehow.

**Comment by p-a-s-c-a-l** [comment]
See also https://github.com/clarity-h2020/scenario-analysis/issues/9#issuecomment-468696767

**Comment by stefanon** [comment]
@patrickkaleta Hi Patrick

> CLARITY impact table at https://csis.myclimateservice.eu/study/1/step/22/view/table shows unplausible >results

yes, I agree

> E.g., the sum of all “old” people (D1++ D5) is ca. 100k for 28° and ca. 20k for 34°. The rest moved out? :-D

here I see a problem: the sum of all 'old' people is **sum(D1..D5) + D0**, where **D0** are the unaffected people (D0: no damage), that you aren't taking in account, and that is not shown in the table at the link, as probably it's showing only classes with damage > 0 (_Damage level estimates for the selected hazard_). 
What it's not working, also with fake  damage level probability functions, is (from online table data that I see now, for 34° and 30° HW): 

![image](https://user-images.githubusercontent.com/9317034/55087224-0a5c6300-50aa-11e9-9cf8-2937924065cc.png)

you can see that damage for lower temperatures is higher than that for higher temperature.

If I can add more, there is a typo in the selection list and data, where there's 'Haet' instead of Heat, and if also the data tables could be sorted in the same way for 'vulnerab.classes' field, the comparison would be easier.

**Comment by DenoBeno** [comment]
This is still broken, @humerh @stefanon could you please fix this?
@alecapolupo says that even the current curves should give *plausible* results, whereas we see less people dying with higher temperatures. 

Maybe they all went to the sea (incredibly good model?)?

**Comment by stefanon** [comment]
@bernhardsk is there a way I can see how those damage level probability functions are coded in EMIKAT?

**Comment by bernhardsk** [comment]
Summary: The damage level probability functions (DLPFs) aka. vulnerability functions are now "fixed": 

* The sum of all people per vulnerability class accross all damage levels always add up to 100% ot people of that vulnerability class. 
* Higher temperatures do not lead to lower amounts of people affected any more. This was because we had not copied the 1 available set of DLPFs (for 36°C) accross the whole range of temperatures resulting after the local effects calculation. The implementation in EMIKAT now shows the correct behaviour: the number of people affected will not change with higher/lower hazard event temperatures (as currently only 1 set of DLPFs is used and copied for each temperature). @alecapolupo & @stefanon  please check =) 

After that I will import the more realistic dummy values (higher temperatures lead to more people being affected). 
This will change what looks currently similar to this : 
![grafik](https://user-images.githubusercontent.com/42140898/56684252-a8eeda80-66cf-11e9-8759-e18480c7028f.png)

to something similar to this:
![grafik](https://user-images.githubusercontent.com/42140898/56684272-b2784280-66cf-11e9-9130-fd5dd23eafaf.png)


Currently:
28°C: 
![grafik](https://user-images.githubusercontent.com/42140898/56646035-0870ca00-667f-11e9-9203-f0ee5ad79a35.png)

same for 30°C and 32°C.

34°C:
![grafik](https://user-images.githubusercontent.com/42140898/56646091-276f5c00-667f-11e9-9610-a1ea97ea75c0.png)

@stefanon Dear Stefano, in order to show how the damage level probability functions are set up in EMIKAT we could stay in the GoToMeeting after the telco next monday or tuesday or we show them directly in the telco if this is also of interest for the others. We could also do a separate telco, just let us know when you would be available. 

@patrickkaleta: 
* The typo ('Haet' instead of Heat) was corrected. 
* Regarding "If also the data tables could be sorted in the same way for 'vulnerab.classes' field, the comparison would be easier": You are absolutely right. If you click on the column name "Vulnerability class", the sorting will always be the same. Maybe the sorting here can be set to "Vulnerability class" per default? @therter

**Comment by bernhardsk** [comment]
Quick update: 
More realistically behaving DUMMY damage level probability functions (DLPF) have been implemented in AIT EMIKAT which are shown in Drupal by the table component here: https://csis.myclimateservice.eu/study/1/step/22/view/table 
Increasing hazard event temperatures increase values from higher damage levels while less people fall into the categories of lower damage levels. 

The current DLPFs look similar like the example (people - heat-wave (6 days) - Age 15-65) below:
![grafik](https://user-images.githubusercontent.com/42140898/57710349-0e9a0b00-766d-11e9-8e32-ee468b65f33c.png)

6 consecutive days > 28°C:
![grafik](https://user-images.githubusercontent.com/42140898/57708450-a4cc3200-7669-11e9-9e5c-2578bff33a66.png)

6 consecutive days > 34°C:
![grafik](https://user-images.githubusercontent.com/42140898/57708475-b3b2e480-7669-11e9-8b7b-7b0528f610aa.png)

What is needed are actual/reliable DLPFs.

**Comment by p-a-s-c-a-l** [comment]
> What is needed are actual/reliable DLPFs.

What's the status here?

**Comment by bernhardsk** [comment]
PLINIVS informed us via e-mail that there are some updates related to vulnerability functions and the flooding model which will be presented on the second day of the upcoming plenary meeting (until then, some issues are still being finalised).

**Comment by DenoBeno** [comment]
I had a look at various EMIKAT outputs today and following items stroke my eye:

- data showing correctly in "data" and "geojson" views, but wrong data shown in "csv" view. Noticed this for the damage calculations.
- occasional negative data, e.g. -1 for the population in a cell, also for the damage.
